# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: We are all the one
email: wilburwilliams7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Our mission at iamthe1.cc is to help the people of the 
  world find and unlock their innate human potential. 
  We believe that all humans have the gene of greatness inside of them.
  It is simply up to us, the messengers, to guide our people towards the light.
  This is iamthe1.cc
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: We_are_the1
facebook_username:  InnerTruth1

# Build settings
markdown: kramdown
